import type { Metadata } from "next";
import "@/styles/reset.css";
import "@/styles/globals.css";
import { openSans } from "@/shared/config/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans}`}>
        {children}
      </body>
    </html>
  );
}
